---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: string-flag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: false

conditions:
  - allOf:
      - flag:
          name: booleanFlagRomain
          value: "false"
    flagValue:
      valueWrittenInCode: false
